- .circleci/config.yml
Use the CI system to deploy documentation to the `gh-pages` branch of this repo. This will
allow documentation off master to be available at all times.
> [docs] publish rustdocs through CircleCI

- guppy/README.md
- guppy/README.tpl
The documentation for `master` is hosted on GitHub Pages and automatically updated through CI. Adda link to it.
> [guppy] add link from readme to documentation

- guppy/README.md
- guppy/examples/deps.rs
- guppy/examples/print_dot.rs
- guppy/examples/remove_dev_only.rs
- guppy/src/lib.rs
This means users can easily run these examples with `cargo run --example foo`.
> [guppy] move example snippets into examples dir

- guppy/examples/remove_dev_only.rs
We filter out all dev-only links, not just those within the workspace.
> [guppy] small fix to remove_dev_only example

- README.md
> [readme] add a link to the docs for guppy to the root README

- guppy/Cargo.toml
This prevented version 0.1.0 from being published. Updated the version number as well.
> [guppy] fix keywords

- cargo-guppy/Cargo.toml
- cargo-guppy/src/lib.rs
- cargo-guppy/src/main.rs
- guppy/src/graph/select.rs
This adds `cargo guppy select` to get lists of packages, filter the list, and create DOT graph output.
> Implement select command to query dependencies

- cargo-guppy/src/lib.rs
- cargo-guppy/src/main.rs
This adds a command which reports the unique dependency count for every
subtree in the graph. This is the count and the list of dependencies brought
in uniquely through this subtree.
This also refactors and reuses the graph narrowing code and filtering options
from the select command.
> [cargo-guppy] Add subtree-size command

- cargo-guppy/src/lib.rs
- cargo-guppy/src/main.rs
While exploring Libra's dependency graph I found some bugs and made a number of improvements:
- enable filter options on dups command
- added filter options for direct third-party dependencies
- remove the count command, which duplicates select and can be replaced by `... | wc -l`
- worked around bug with cyclic graph by iterating over edges instead of nodes
- fixed a bug with root set selection
> cargo guppy commandline improvements

- cargo-guppy/src/lib.rs
Remove the workarounds put in place for cyclic graphs now that guppy handles them correctly.
> [cargo-guppy] Remove cyclic graph workarounds

- guppy/Cargo.toml
- guppy/src/graph/graph_impl.rs
- guppy/src/petgraph_support/scc.rs
A `Nested` can be used to flatten out a `Vec<Vec<T>>` by storing it inline along with indexes. This is perfect for SCCs.
On top of making the code much simpler, this is a nice performance boost:
```
into_iter_ids           time:   [410.64 us 418.96 us 426.89 us]
change: [-14.866% -12.965% -10.966%] (p = 0.00 < 0.05)
Performance has improved.
```
> [guppy] use Nested to store SCCs

- cargo-guppy/src/lib.rs
Introduced when I removed the workaround for cyclic graphs. I forgot to ensure the dep pointed from the workspace to out of the workspace.
> [cargo-guppy] Fix bug in direct deps calculation

- target-spec/Cargo.toml
i.e. don't use the "lexical" feature, which is only used for floats anyway (so is irrelevant to us).
This reduces the size of the dependency graph.
> [target-spec] only use the std feature for nom

- cargo-guppy/Cargo.toml
- guppy/Cargo.toml
- guppy/src/debug_ignore.rs
- guppy/src/graph/graph_impl.rs
- guppy/src/graph/select.rs
- guppy/src/lib.rs
unfortunately we can't remove `syn` and `quote` altogether from the dependency graph because cargo metadata deserialization relies on them, but we can still speed up build times a bit.
> a few cleanups

- README.md
- guppy/CHANGELOG.md
- guppy/Cargo.toml
- guppy/README.md
- guppy/src/graph/graph_impl.rs
- guppy/src/lib.rs
- target-spec/CHANGELOG.md
- target-spec/Cargo.toml
The repo has moved to the facebookincubator org.
> [admin] update repository links to point to the new location

- cargo-guppy/src/core.rs
- cargo-guppy/src/lib.rs
- cargo-guppy/src/main.rs
Implement a couple of flags that I found useful while trying to figure out why a package was included in the build.
> [cargo-guppy] cleanup + implement --select-reverse and --output-reverse

- cargo-guppy/src/core.rs
- guppy/CHANGELOG.md
- guppy/src/errors.rs
- guppy/src/graph/build.rs
- guppy/src/graph/feature/build.rs
- guppy/src/graph/feature/graph_impl.rs
- guppy/src/graph/feature/resolve.rs
- guppy/src/graph/graph_impl.rs
- guppy/src/graph/mod.rs
- guppy/src/graph/resolve.rs
- guppy/src/graph/resolve_core.rs
- guppy/src/unit_tests/dep_helpers.rs
- guppy/src/unit_tests/fixtures.rs
- guppy/src/unit_tests/graph_tests.rs
I've been a bit unsatisfied by the current design of the way `EnabledStatus` etc work.
* The current design always requires evaluation against a particular platform. We've made this easier by providing the current platform as default, but that is error-prone as #111 points out.
* The current design also doesn't have a way to distinguish between dependencies that are enabled regardless of platform and those that are enabled on a specific platform (but might be disabled on others).
* The API also isn't very orthogonal -- in particular, feature graph resolution caused me to have to introduce the `PlatformStatus` API anyway, and we should try and make that API also work for the package graph.
This new design is an answer to all of those concerns. It introduces three data structures:
* …
> re-do platform-specific statuses 

- guppy/src/graph/feature/build.rs
- guppy/src/graph/graph_impl.rs
- guppy/src/unit_tests/graph_tests.rs
`has_build_script` ended up being important (see https://github.com/libra/libra/pull/3595)
> Some more improvements

- benchmarks/benches/package_graph.rs
- cargo-guppy/src/lib.rs
- guppy/examples/deps.rs
- guppy/examples/print_dot.rs
- guppy/examples/remove_dev_only.rs
- guppy/examples/topo_sort.rs
- guppy/src/graph/feature/graph_impl.rs
- guppy/src/graph/feature/resolve.rs
- guppy/src/graph/resolve.rs
- guppy/src/graph/resolve_core.rs
- guppy/src/petgraph_support/scc.rs
- guppy/src/unit_tests/dep_helpers.rs
- guppy/src/unit_tests/graph_tests.rs
- guppy/src/unit_tests/proptest_helpers.rs
These started off as consuming when we didn't have resolve sets as a first-class concept, but they no longer need to be.
> [guppy] make resolve set iterators nonconsuming

- cargo-guppy/src/core.rs
- cargo-guppy/src/lib.rs
- guppy/README.md
- guppy/examples/deps.rs
- guppy/examples/print_by_level.rs
- guppy/examples/print_dot.rs
- guppy/examples/remove_dev_only.rs
- guppy/src/graph/build.rs
- guppy/src/graph/feature/build.rs
- guppy/src/graph/graph_impl.rs
- guppy/src/graph/mod.rs
- guppy/src/graph/proptest09.rs
- guppy/src/graph/resolve.rs
- guppy/src/lib.rs
- guppy/src/unit_tests/dep_helpers.rs
- guppy/src/unit_tests/fixtures.rs
- guppy/src/unit_tests/graph_tests.rs
The link/edge distinction made more sense in a world where we were returning
references directly, but now we return wrapper structs.
> [graph] remove PackageEdge, subsume its functionality into PackageLink

- cargo-guppy/src/diff.rs
- cargo-guppy/src/lib.rs
- guppy/README.md
- guppy/examples/deps.rs
- guppy/examples/print_by_level.rs
- guppy/examples/print_dot.rs
- guppy/examples/remove_dev_only.rs
- guppy/src/graph/build.rs
- guppy/src/graph/feature/build.rs
- guppy/src/graph/feature/graph_impl.rs
- guppy/src/graph/feature/resolve.rs
- guppy/src/graph/graph_impl.rs
- guppy/src/graph/resolve.rs
- guppy/src/lib.rs
- guppy/src/unit_tests/dep_helpers.rs
- guppy/src/unit_tests/fixtures.rs
- guppy/src/unit_tests/graph_tests.rs
- guppy/src/unit_tests/proptest_helpers.rs
In practice this is how most people end up using these methods.
> remove retain_edges, move direct dependency queries to PackageMetadata

- guppy/src/dependency_kind.rs
- guppy/src/errors.rs
- guppy/src/graph/build.rs
- guppy/src/graph/feature/graph_impl.rs
- guppy/src/graph/graph_impl.rs
- guppy/src/graph/mod.rs
- guppy/src/lib.rs
- guppy/src/metadata_command.rs
- guppy/src/unit_tests/dep_helpers.rs
- guppy/src/unit_tests/fixtures.rs
This allows us to impose some constraints on what is required, and upgrade `cargo_metadata` without breaking semver compat.
> Make cargo_metadata a private dependency

- cargo-guppy/src/core.rs
- cargo-guppy/src/lib.rs
- guppy/src/graph/cargo.rs
- guppy/src/graph/feature/query.rs
- tools/cargo-compare/src/common.rs
Add `--omit-edges-into`, `--build-kind` for host/target and `--kind`.
This ended up being a breaking change because of `&mut` in `CargoOptions` -- ah well. We'll live, and it's probably more useful to have the `&mut` than not.
> [cargo-guppy] Bring resolve-cargo to mostly feature parity with select

- cargo-guppy/src/core.rs
- cargo-guppy/src/lib.rs
- guppy-cmdlib/src/lib.rs
This allows for the v2 resolver to be activated as necessary.
> [cargo-guppy] add resolve-cargo --resolver-version

- guppy-summaries/src/diff.rs
We can safely discard the old values in all of these cases.
> [guppy-summaries] fix lint issues with mem::replace

- Cargo.lock
- cargo-guppy/Cargo.toml
- fixtures/src/dep_helpers.rs
- fixtures/src/details.rs
- fixtures/src/json.rs
- guppy/CHANGELOG.md
- guppy/Cargo.toml
- guppy/src/graph/cycles.rs
- guppy/src/graph/feature/cycles.rs
- guppy/src/graph/feature/graph_impl.rs
- guppy/src/graph/feature/resolve.rs
- guppy/src/graph/graph_impl.rs
- guppy/src/graph/resolve.rs
- guppy/src/petgraph_support/mod.rs
- guppy/src/petgraph_support/scc.rs
- guppy/src/petgraph_support/topo.rs
- internal-tools/benchmarks/benches/package_graph.rs
- target-spec/CHANGELOG.md
- target-spec/Cargo.toml
- tools/determinator/Cargo.toml
- tools/hakari/Cargo.toml
Before this PR, packages in cycles could be returned in arbitrary
order. But there is a natural order to return them in: non-dev order.
This is not a breaking change because it's just an additional API constraint
on guppy that didn't exist before.
Constructing cycles does become slower as a result, but it's still
pretty fast. There's likely more scope for optimization in the future.
```
make_cycles             time:   [118.21 us 119.18 us 120.11 us]
change: [+77.496% +78.481% +79.512%] (p = 0.00 < 0.05)
```
> [guppy] return packages in cycles in non-dev order

- guppy/src/errors.rs
Don't display errors that are returned in the `source` method.
> [guppy] improve Error Display impl

- Cargo.lock
- guppy-summaries/src/summary.rs
- guppy/src/graph/cargo/cargo_api.rs
- internal-tools/cargo-compare/Cargo.toml
- tools/determinator/src/rules.rs
Ships with Rust 1.51, which has the new feature resolver.
> upgrade to cargo 0.52.0

- .github/workflows/ci.yml
They depend on the cargo version matching the builtin list in cfg-expr.
> [ci] restrict cargo-compare tests to cfg-expr version

- Cargo.lock
- guppy/Cargo.toml
- guppy/src/graph/build.rs
- guppy/src/graph/graph_impl.rs
The package.rust-version field was added to Cargo in Rust 1.56. When a package author specifies this field, they promise the package can be compiled with at least the specified Rust version.
The cargo_metadata crate was bumped from 0.14.0 to 0.14.1, since that's the first version of cargo_metadata which added support for the `rust-version` field.
I would be more than happy to add test cases, as requested in the contributor guidelines, but wasn't entirely sure where the best place would be (I couldn't find tests for the other PackageMetadata fields to use as a reference). Possibly I could add a test module for package metadata tests in `guppy::unit_tests`, and then mock the dependencies for PackageMetadata.
> Add rust-version support to PackageMetadata

- Cargo.lock
- guppy-summaries/src/summary.rs
- guppy/Cargo.toml
- guppy/src/graph/build.rs
- guppy/src/graph/summaries/package_set.rs
- tools/determinator/src/determinator.rs
- tools/determinator/tests/determinator_tests.rs
- tools/hakari/src/toml_out.rs
Use forward slashes for *relative* paths while continuing to use
canonical separators for absolute paths. This keeps the internal logic
simpler.
>  [guppy] use forward slashes for relative paths on all platforms, including Windows

- target-spec/CHANGELOG.md
Folks can upgrade to version 1 pretty easily, no point in this.
> [target-spec] remove note about 0.9.1

- .github/workflows/ci.yml
Also switch to the new cargo-install action for installs, and build the
guppy-summaries crate (and remove the cargo-guppy crate from the core
set).
> [ci] switch to cargo-nextest for builds

- .github/workflows/ci.yml
Apparently actions-rs/toolchain chokes on "1.60" and interprets it as "1.6" -- fix it to use "1.60.0".
> [ci] work around bug in actions-rs/toolchain version spec
