- .circleci/config.yml
Whoops, too little adaptation :)
> [circleci] fix path in docs-deploy

- .circleci/config.yml
> [circleci] move add_ssh_keys to before the final deploy

- guppy/Cargo.toml
- guppy/src/graph/select.rs
This shouldn't be a breaking change.
Closes #41.
> [select] IntoIterator -> Iterator

- .circleci/config.yml
- cargo-guppy/src/lib.rs
- guppy/Cargo.toml
- guppy/src/errors.rs
- guppy/src/graph/build.rs
- guppy/src/graph/feature.rs
- guppy/src/graph/graph_impl.rs
- guppy/src/graph/mod.rs
- guppy/src/graph/proptest09.rs
- guppy/src/graph/select.rs
- guppy/src/petgraph_support/mod.rs
- guppy/src/petgraph_support/walk.rs
- guppy/src/unit_tests/proptest_helpers.rs
The changes are to prepare for upcoming feature graph work.
> Fix into_root_ids and into_root_metadatas + some other changes

- Cargo.toml
- benchmarks/.gitignore
- benchmarks/Cargo.toml
- benchmarks/benches/package_graph.rs
- benchmarks/src/lib.rs
- guppy/src/graph/feature.rs
- guppy/src/graph/mod.rs
- guppy/src/graph/select.rs
The depends_on cache is a pretty significant speedup!
> Add a couple of initial benchmarks

- guppy/src/graph/feature/graph_impl.rs
- guppy/src/graph/feature/select.rs
- guppy/src/unit_tests/dep_helpers.rs
- guppy/src/unit_tests/proptest_helpers.rs
Also add proptests to ensure this returns the same results as into_root_ids.
> [feature] implement into_root_metadatas

- guppy/src/graph/feature/build.rs
> [feature] fix dev edge in FeatureEdge

- guppy/Cargo.toml
Brings in new versions of syn/quote etc.
> [guppy] upgrade to derivative 2

- Cargo.toml
- cargo-guppy/Cargo.toml
- target-spec/Cargo.toml
- target-spec/README.md
- target-spec/README.tpl
- target-spec/src/evaluator.rs
- target-spec/src/lib.rs
- target-spec/src/parser.rs
- target-spec/src/tests.rs
- target-spec/src/types.rs
Import https://github.com/metajack/target-spec/commit/1609fb5f9e3876415e64832e26260d2faf936f72 and clean it up for publishing.
> Add source code for target-spec crate

- guppy/src/graph/feature/resolve.rs
- guppy/src/graph/resolve.rs
- guppy/src/graph/resolve_core.rs
- guppy/src/graph/select_core.rs
- guppy/src/unit_tests/dep_helpers.rs
- guppy/src/unit_tests/fixtures.rs
- guppy/src/unit_tests/proptest_helpers.rs
Implement:
* `len` and `is_empty`
* `contains`
* `union`, `intersection`, `difference` and `symmetric_difference`
> [graph] implement set operations

- Cargo.lock
- cargo-guppy/src/lib.rs
- guppy/CHANGELOG.md
- guppy/Cargo.toml
- guppy/examples/deps.rs
- guppy/examples/print_dot.rs
- guppy/examples/topo_sort.rs
- guppy/src/graph/feature/resolve.rs
- guppy/src/graph/feature/select.rs
- guppy/src/graph/graph_impl.rs
- guppy/src/graph/resolve.rs
- guppy/src/graph/select.rs
- guppy/src/unit_tests/dep_helpers.rs
- guppy/src/unit_tests/proptest_helpers.rs
Do some more cleanups before shipping the new version.
> [guppy] prepare for version 0.1.8

- guppy/README.md
- guppy/src/graph/feature/graph_impl.rs
- guppy/src/graph/feature/query.rs
- guppy/src/graph/feature/resolve.rs
- guppy/src/graph/resolve.rs
- guppy/src/graph/resolve_core.rs
- guppy/src/lib.rs
- guppy/src/petgraph_support/mod.rs
- guppy/src/unit_tests/graph_tests.rs
- guppy/src/unit_tests/proptest_helpers.rs
These methods provide ways to switch between the two graphs.
> Implement conversions between PackageSet and FeatureSet

- Cargo.lock
- target-spec/CHANGELOG.md
- target-spec/Cargo.toml
- target-spec/src/evaluator.rs
- target-spec/src/parser.rs
- target-spec/src/platform.rs
This turns out to be an issue in practice.
> [target-spec] handling unknown flags

- guppy/Cargo.toml
The new version of target-spec fixes some stuff so bump that up as well.
> [guppy] a couple of fixes to Cargo.toml

- guppy/src/graph/build.rs
- guppy/src/graph/feature/build.rs
- guppy/src/graph/graph_impl.rs
- guppy/src/graph/mod.rs
- guppy/src/graph/proptest09.rs
- guppy/src/graph/query.rs
- guppy/src/graph/resolve.rs
- guppy/src/unit_tests/dep_helpers.rs
- guppy/src/unit_tests/fixtures.rs
We need to do some more breaking changes, so let's get this one out of the way.
> Simplify PackageEdge

- cargo-guppy/src/core.rs
- guppy/examples/remove_dev_only.rs
- guppy/src/graph/build.rs
- guppy/src/graph/build_targets.rs
- guppy/src/graph/feature/query.rs
- guppy/src/graph/feature/resolve.rs
- guppy/src/graph/proptest09.rs
- guppy/src/graph/query.rs
- guppy/src/graph/query_core.rs
- guppy/src/graph/resolve.rs
- guppy/src/graph/resolve_core.rs
- guppy/src/lib.rs
- guppy/src/petgraph_support/dfs.rs
- guppy/src/petgraph_support/mod.rs
- guppy/src/petgraph_support/reversed.rs
- guppy/src/sorted_set.rs
- guppy/src/unit_tests/fixtures.rs
- guppy/src/unit_tests/graph_tests.rs
- guppy/src/unit_tests/invalid_tests.rs
- guppy/src/unit_tests/proptest_helpers.rs
The most interesting one is that `PackageResolver` is now `&mut self` (and `resolve_with_fn` takes a `FnMut`).
> Some preparation and improvements for Cargo resolution work

- guppy/src/graph/feature/build.rs
- guppy/src/graph/feature/graph_impl.rs
- guppy/src/graph/feature/query.rs
- guppy/src/graph/feature/resolve.rs
- guppy/src/graph/graph_impl.rs
Required for feature resolution and Cargo simulations.
> Add support for cross-package links and feature resolvers

- Cargo.lock
- guppy/CHANGELOG.md
- guppy/Cargo.toml
- guppy/examples/topo_sort.rs
- guppy/src/graph/feature/resolve.rs
- guppy/src/graph/query.rs
- guppy/src/graph/resolve.rs
- guppy/src/graph/resolve_core.rs
- guppy/src/petgraph_support/mod.rs
Meant to add these methods to guppy 0.4.0, but oh well.
> [guppy] add more resolve_ methods

- guppy/src/graph/cargo.rs
This makes it easy to write postfilters inline.
> [guppy] add a convenience wrapper for a postfilter fn

- Cargo.lock
- cargo-guppy/src/lib.rs
- cargo-guppy/src/main.rs
- guppy/Cargo.toml
- guppy/src/graph/cargo.rs
- guppy/src/metadata_command.rs
> A bunch more improvements

- Cargo.lock
- tools/cargo-compare/Cargo.toml
- tools/cargo-compare/src/diff.rs
Use something more sophisticated than a plain `Debug` impl.
> [cargo-compare] better diff presentation

- Cargo.lock
- guppy/Cargo.toml
- guppy/src/graph/cargo.rs
- guppy/src/graph/feature/graph_impl.rs
Proc macros are built on the host, not the target.
> [guppy] fix cargo set computation for proc macros

- Cargo.lock
- guppy/Cargo.toml
- guppy/src/graph/cargo.rs
- tools/cargo-compare/Cargo.toml
- tools/cargo-compare/src/diff.rs
- tools/cargo-compare/src/tests/proptest_helpers.rs
Whoops, we weren't checking if the test actually failed.
Note that this found at least one issue in cargo's v2 resolver (https://github.com/rust-lang/cargo/issues/8312). Can't land until the issue is fixed, and it may find more.
> [cargo-compare] fix proptests

- Cargo.lock
- cargo-guppy/src/lib.rs
- guppy-cmdlib/src/lib.rs
- guppy/src/graph/cargo.rs
- guppy/src/graph/feature/graph_impl.rs
- tools/cargo-compare/Cargo.toml
- tools/cargo-compare/src/common.rs
* Do v2 resolution in two phases, like the v1 resolver.
* (this leads to) add a flag which enables building initial proc macros on the target platform.
> [guppy] further improvements to the v2 resolver

- Cargo.lock
- Cargo.toml
- fixtures/Cargo.toml
- fixtures/src/dep_helpers.rs
- fixtures/src/details.rs
- fixtures/src/json.rs
- fixtures/src/lib.rs
- guppy/Cargo.toml
- guppy/src/graph/feature/graph_impl.rs
- guppy/src/graph/feature/resolve.rs
- guppy/src/graph/graph_impl.rs
- guppy/src/graph/proptest010.rs
- guppy/src/unit_tests/mod.rs
- guppy/tests/graph-tests/feature_helpers.rs
- guppy/tests/graph-tests/graph_tests.rs
- guppy/tests/graph-tests/invalid_tests.rs
- guppy/tests/graph-tests/main.rs
- guppy/tests/graph-tests/proptest_helpers.rs
As part of the test plan for guppy summaries, we're going to
write a small tool to generate a few summaries for each fixture.
> [guppy] move fixtures into their own crate

- cargo-guppy/src/lib.rs
- fixtures/src/dep_helpers.rs
- fixtures/src/details.rs
- guppy-summaries/CHANGELOG.md
- guppy-summaries/Cargo.toml
- guppy/CHANGELOG.md
- guppy/src/errors.rs
- guppy/src/graph/cargo/build.rs
- guppy/src/graph/cargo/cargo_api.rs
- guppy/src/graph/cargo/summaries.rs
- guppy/src/graph/cycles.rs
- guppy/src/graph/feature/cycles.rs
- guppy/src/graph/feature/graph_impl.rs
- guppy/src/graph/feature/query.rs
- guppy/src/graph/feature/resolve.rs
- guppy/src/graph/graph_impl.rs
- guppy/src/graph/query.rs
- guppy/src/graph/resolve.rs
- guppy/tests/graph-tests/feature_helpers.rs
- guppy/tests/graph-tests/graph_tests.rs
- target-spec/CHANGELOG.md
- tools/cargo-compare/src/common.rs
- tools/fixture-manager/src/summaries.rs
Going to do a release after ensuring it works well in x.
> Some cleanups to prepare for guppy 0.5 release

- cargo-guppy/src/lib.rs
- guppy/src/graph/cargo/build.rs
- guppy/src/graph/cargo/cargo_api.rs
- guppy/src/graph/feature/graph_impl.rs
- guppy/src/graph/feature/query.rs
- guppy/src/graph/feature/resolve.rs
- guppy/src/graph/graph_impl.rs
- guppy/src/graph/mod.rs
- guppy/src/graph/query.rs
- guppy/src/graph/query_core.rs
- guppy/src/graph/resolve.rs
- guppy/src/lib.rs
- guppy/src/macros.rs
- guppy/src/obs.rs
- guppy/src/sorted_set.rs
> More fixes

- Cargo.lock
- guppy-summaries/CHANGELOG.md
- guppy/CHANGELOG.md
- guppy/Cargo.toml
- guppy/src/errors.rs
- guppy/src/graph/cargo/summaries.rs
- guppy/src/graph/feature/query.rs
- guppy/src/graph/query.rs
- guppy/src/graph/resolve.rs
- release.toml
A few more improvements inspired by real use cases in x.
> Even more fixes to guppy

- Cargo.lock
- cargo-guppy/Cargo.toml
- cargo-guppy/src/lib.rs
- cargo-guppy/src/main.rs
- cargo-guppy/src/mv.rs
- guppy-summaries/README.md
- guppy-summaries/src/diff.rs
- guppy-summaries/src/lib.rs
- guppy-summaries/src/report.rs
- guppy-summaries/src/summary.rs
- guppy-summaries/src/unit_tests/basic_tests.rs
- guppy/src/metadata_command.rs
- tools/fixture-manager/src/summaries.rs
Feature request by @spacekookie.
> Implement a command to move crates around within a workspace

- .circleci/config.yml
- cargo-guppy/README.md
- cargo-guppy/src/lib.rs
- guppy/README.md
- scripts/regenerate-readmes.sh
- target-spec/README.md
Got pretty frustrated with readmes not being kept up to date.
> Update readmes + add CI

- guppy/src/metadata_command.rs
Add impls for `MetadataCommand` and `CargoMetadata`.
> [guppy] add TryFrom impls for metadata -> PackageGraph

- .github/workflows/ci.yml
- Cargo.lock
- guppy/Cargo.toml
- target-spec/CHANGELOG.md
- target-spec/Cargo.toml
- target-spec/build.rs
Also add CI coverage.
Fixes #175.
> [target-spec] Fix build on aarch64

- .github/workflows/ci.yml
> [ci] exclude cargo-compare from aarch64 build set

- .github/workflows/ci.yml
Both have weird path differences, would be good to have them be checked too.
> [ci] run on mac and windows as well

- Cargo.lock
The new lockfile format has been turned on by default.
> [cargo] update lockfile format

- tools/determinator/src/determinator.rs
- tools/determinator/src/paths0.rs
You can just delete a file without affecting any others, breaking the build.
> [determinator] update help to also recommend passing in deleted files

- Cargo.lock
- tools/hakari/Cargo.toml
- tools/hakari/src/cargo_toml.rs
Avoid bumping the mtime, and always leave the repository in a consistent state.
> [hakari] use atomic write for Cargo.toml, and don't update if not necessary

- Cargo.lock
- fixtures/guppy/summaries/metadata_guppy_78cb7e8-6.toml
- fixtures/guppy/summaries/metadata_guppy_869476c-6.toml
- fixtures/guppy/summaries/metadata_guppy_c9b4f76-6.toml
- fixtures/large/summaries/metadata_libra-6.toml
- fixtures/large/summaries/metadata_libra_9ffd93b-6.toml
- fixtures/large/summaries/metadata_libra_f0091a4-6.toml
- fixtures/small/summaries/metadata1-6.toml
- fixtures/small/summaries/metadata2-6.toml
- fixtures/small/summaries/metadata_build_targets1-6.toml
- fixtures/small/summaries/metadata_cycle1-6.toml
- fixtures/small/summaries/metadata_cycle2-6.toml
- fixtures/small/summaries/metadata_cycle_features-6.toml
- fixtures/small/summaries/metadata_dups-6.toml
- fixtures/small/summaries/metadata_proc_macro1-6.toml
- fixtures/small/summaries/metadata_targets1-6.toml
- target-spec/Cargo.toml
Update third-party transitive deps + cfg-expr.
> Dependency updates

- guppy/Cargo.toml
- guppy/src/graph/cargo/cargo_api.rs
- tools/hakari/Cargo.toml
- tools/hakari/README.md
- tools/hakari/README.tpl
- tools/hakari/src/hakari.rs
- tools/hakari/src/lib.rs
- tools/hakari/src/toml_out.rs
Rename a few types and add some documentation for hakari.
> [meta] documentation updates and renames

- Cargo.lock
- cargo-guppy/Cargo.toml
- guppy/CHANGELOG.md
- guppy/Cargo.toml
- guppy/src/graph/cargo/cargo_api.rs
- guppy/src/metadata_command.rs
- target-spec/CHANGELOG.md
- target-spec/Cargo.toml
- tools/determinator/CHANGELOG.md
- tools/determinator/Cargo.toml
- tools/determinator/src/determinator.rs
- tools/hakari/CHANGELOG.md
- tools/hakari/Cargo.toml
- tools/hakari/README.md
- tools/hakari/src/lib.rs
Including the first version of hakari!
> release new versions of most things

- Cargo.lock
- guppy/Cargo.toml
- guppy/tests/graph-tests/invalid_tests.rs
> [guppy] replace assert_matches!(...) with assert!(matches!(...))

- .github/workflows/ci.yml
- Cargo.lock
- README.md
- guppy/CHANGELOG.md
- guppy/Cargo.toml
- guppy/src/petgraph_support/topo.rs
- internal-tools/cargo-compare/Cargo.toml
- internal-tools/cargo-compare/proptest-regressions/tests/workspace_tests.txt
Also document and test the MSRV policy.
> [guppy] restore compatibility with Rust 1.48

- .github/dependabot.yml
- .github/workflows/ci.yml
* Fix absurd behavior of actions/checkout.
* Also upgrade transitive deps in Cargo.lock.
> [ci] updates to CI

- Cargo.lock
- guppy-cmdlib/Cargo.toml
- guppy-cmdlib/src/lib.rs
- guppy/Cargo.toml
- guppy/README.md
- guppy/src/graph/build.rs
- guppy/src/graph/build_targets.rs
- guppy/src/graph/cargo/cargo_api.rs
- guppy/src/graph/feature/mod.rs
- guppy/src/graph/feature/proptest_helpers.rs
- guppy/src/graph/graph_impl.rs
- guppy/src/graph/mod.rs
- guppy/src/graph/proptest_helpers.rs
- guppy/src/lib.rs
- guppy/tests/graph-tests/main.rs
- internal-tools/benchmarks/Cargo.toml
- internal-tools/cargo-compare/Cargo.toml
- internal-tools/fixture-manager/Cargo.toml
- internal-tools/proptest-ext/Cargo.toml
- target-spec/Cargo.toml
- target-spec/src/lib.rs
- target-spec/src/proptest.rs
- target-spec/src/summaries.rs
- tools/hakari/Cargo.toml
- tools/hakari/src/hakari.rs
- tools/hakari/src/lib.rs
- tools/hakari/src/proptest_helpers.rs
This is a public API so it is a breaking change.
> [proptest] upgrade to 1.0.0

- Cargo.lock
- cargo-guppy/Cargo.toml
- cargo-guppy/src/mv.rs
- fixtures/Cargo.toml
- fixtures/small/hakari/metadata2-3.toml
- fixtures/small/hakari/metadata2-5.toml
- fixtures/src/details.rs
- guppy-summaries/CHANGELOG.md
- guppy-summaries/Cargo.toml
- guppy-summaries/src/summary.rs
- guppy/CHANGELOG.md
- guppy/Cargo.toml
- guppy/examples/topo_sort.rs
- guppy/src/errors.rs
- guppy/src/graph/build.rs
- guppy/src/graph/graph_impl.rs
- guppy/src/graph/query.rs
- guppy/src/graph/resolve.rs
- target-spec/CHANGELOG.md
- target-spec/Cargo.toml
- tools/determinator/CHANGELOG.md
- tools/determinator/Cargo.toml
- tools/determinator/README.md
- tools/determinator/src/determinator.rs
- tools/determinator/src/lib.rs
- tools/determinator/src/paths0.rs
- tools/determinator/tests/determinator_tests.rs
- tools/hakari/CHANGELOG.md
- tools/hakari/Cargo.toml
- tools/hakari/src/toml_out.rs
guppy was a good testing ground for camino.
> switch path APIs to camino

- guppy/CHANGELOG.md
- guppy/src/dependency_kind.rs
- guppy/src/graph/build.rs
- guppy/src/graph/graph_impl.rs
* Add a way to list out all the values of DependencyKind.
* Add a `no_default_features` method.
> [guppy] some improvements to DependencyReq

- Cargo.lock
- cargo-guppy/Cargo.toml
- fixtures/Cargo.toml
- fixtures/src/details.rs
- fixtures/src/json.rs
- guppy-summaries/Cargo.toml
- guppy/CHANGELOG.md
- guppy/Cargo.toml
- guppy/src/graph/build.rs
- guppy/src/graph/build_targets.rs
- guppy/src/graph/graph_impl.rs
- internal-tools/fixture-manager/Cargo.toml
- internal-tools/fixture-manager/src/context.rs
- internal-tools/fixture-manager/src/hakari_toml.rs
- internal-tools/fixture-manager/src/lib.rs
- internal-tools/fixture-manager/src/summaries.rs
- internal-tools/fixture-manager/tests/unchanged_tests.rs
- tools/determinator/CHANGELOG.md
- tools/determinator/Cargo.toml
- tools/hakari/CHANGELOG.md
- tools/hakari/Cargo.toml
- tools/hakari/src/cargo_toml.rs
- Upgrade cargo_metadata
- A few API improvements (closes #320 in particular).
> A bunch more changes

- target-spec/src/triple.rs
- tools/cargo-hakari/README.md
- tools/cargo-hakari/README.tpl
Filed upstream as https://github.com/bytecodealliance/target-lexicon/issues/78
> fix issue with target-lexicon diverging from builtins

- .github/workflows/hakari.yml
This is going to be used as an example by folks.
> [ci] update hakari.yml to use public version of cargo-hakari

- .github/workflows/hakari.yml
Going to be used as an example.
> [ci] update hakari.yml

- tools/hakari/src/hakari.rs
Only need to look at "none" and "all" because of the
structure-preserving behavior.
Verified by the fact that none of the generated outputs change.
> [hakari] don't look at default features

- .config/hakari.toml
- .github/workflows/ci.yml
- .github/workflows/docs.yml
- Cargo.lock
- cargo-guppy/Cargo.toml
- fixtures/Cargo.toml
- guppy-cmdlib/Cargo.toml
- guppy-summaries/Cargo.toml
- guppy/CHANGELOG.md
- guppy/Cargo.toml
- internal-tools/benchmarks/Cargo.toml
- internal-tools/fixture-manager/Cargo.toml
- internal-tools/proptest-ext/Cargo.toml
- target-spec/Cargo.toml
- tools/cargo-hakari/CHANGELOG.md
- tools/cargo-hakari/Cargo.toml
- tools/cargo-hakari/README.md
- tools/cargo-hakari/src/command.rs
- tools/cargo-hakari/src/docs/publishing.rs
- tools/cargo-hakari/src/lib.rs
- tools/determinator/Cargo.toml
- tools/hakari/CHANGELOG.md
- tools/hakari/Cargo.toml
- tools/hakari/README.md
- tools/hakari/src/lib.rs
- workspace-hack/Cargo.toml
Unfortunately, while trying to use it on the diem repository I ran into #524 :(
> Revert change to target a common workspace-hack crate

- .github/workflows/ci.yml
> [ci] use Swatinem/rust-cache

- cargo-guppy/src/core.rs
- guppy-cmdlib/src/lib.rs
- tools/cargo-hakari/src/command.rs
> [meta] remove number_of_values

- .github/workflows/ci.yml
- tools/cargo-hakari/src/command.rs
Also ensure that the toolchain's overridden properly.
> [cargo-hakari] replace some more structopt instances with clap

- .github/workflows/docs.yml
- .github/workflows/release.yml
- Cargo.lock
- cargo-guppy/Cargo.toml
- guppy-summaries/Cargo.toml
- guppy/CHANGELOG.md
- guppy/Cargo.toml
- guppy/src/graph/cargo/build.rs
- guppy/src/graph/feature/build.rs
- guppy/src/graph/feature/graph_impl.rs
- guppy/src/graph/feature/query.rs
- guppy/src/graph/feature/resolve.rs
- guppy/src/lib.rs
- tools/cargo-hakari/CHANGELOG.md
- tools/cargo-hakari/Cargo.toml
- tools/determinator/Cargo.toml
- tools/hakari/CHANGELOG.md
- tools/hakari/Cargo.toml
Add release jobs to publish releases to github.
> [guppy] rename CrossLink to ConditionalLink + prepare for releases

- guppy-summaries/src/summary.rs
- guppy/src/graph/build.rs
- guppy/src/graph/graph_impl.rs
> [guppy] fix cross-drive path diffs on Windows
